export const teamMap = {
  teamA1: { name: 'Tyskland', group: 'A' },
  teamA2: { name: 'Skottland', group: 'A' },
  teamA3: { name: 'Ungarn', group: 'A' },
  teamA4: { name: 'Sveits', group: 'A' },
  teamB1: { name: 'Spania', group: 'B' },
  teamB2: { name: 'Kroatia', group: 'B' },
  teamB3: { name: 'Italia', group: 'B' },
  teamB4: { name: 'Albania', group: 'B' },
  teamC1: { name: 'Slovenia', group: 'C' },
  teamC2: { name: 'Danmark', group: 'C' },
  teamC3: { name: 'Serbia', group: 'C' },
  teamC4: { name: 'England', group: 'C' },
  teamD1: { name: 'Nederland', group: 'D' },
  teamD2: { name: 'Frankrike', group: 'D' },
  teamD3: { name: 'Polen', group: 'D' },
  teamD4: { name: 'Østerrike', group: 'D' },
  teamE1: { name: 'Ukraina', group: 'E' },
  teamE2: { name: 'Slovakia', group: 'E' },
  teamE3: { name: 'Belgia', group: 'E' },
  teamE4: { name: 'Romania', group: 'E' },
  teamF1: { name: 'Tyrkia', group: 'F' },
  teamF2: { name: 'Portugal', group: 'F' },
  teamF3: { name: 'Georgia', group: 'F' },
  teamF4: { name: 'Tsjekkia', group: 'F' }
};